trigger:
- main  # Branche à partir de laquelle le pipeline sera déclenché

pool:
  vmImage: 'ubuntu-latest'  # Image de machine virtuelle à utiliser

steps:
- task: MavenAuthenticate@0
  displayName: 'Authenticate with Maven'

- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'  # Le fichier pom.xml de votre projet
    options: '-X'  # Options de compilation Maven
    goals: 'clean install'  # Nettoyer et installer les dépendances
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '11'  # Version de JDK, vous pouvez ajuster cela en fonction de votre version
    jdkArchitectureOption: 'x64'
  displayName: 'Build with Maven'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/target/test-*.xml'  # Résultats des tests à publier
    testRunTitle: 'Publish Maven Test Results'
  condition: succeededOrFailed()  # Exécute cette tâche même si les tests échouent
